name: CI

on: [push]

jobs:
  build:

    runs-on

    steps:
    - uses: actions/checkout@v1
    - name: control Domašov
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
